import Stripe from 'stripe';

export const allPaymentMethods = [
  'ach_credit_transfer',
  'ach_debit',
  'acss_debit',
  'affirm',
  'afterpay_clearpay',
  'alipay',
  'au_becs_debit',
  'bacs_debit',
  'bancontact',
  'blik',
  'boleto',
  'card',
  'card_present',
  'cashapp',
  'customer_balance',
  'eps',
  'fpx',
  'giropay',
  'grabpay',
  'ideal',
  'interac_present',
  'klarna',
  'konbini',
  'link',
  'multibanco',
  'oxxo',
  'p24',
  'paynow',
  'paypal',
  'pix',
  'promptpay',
  'revolut_pay',
  'sepa_credit_transfer',
  'sepa_debit',
  'sofort',
  'swish',
  'twint',
  'us_bank_account',
  'wechat_pay',
  'zip',
];

export const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
